export const DEFAULT_CATEGORIES = [
  { name: 'Electronics' },
  { name: 'Mobile Phones' },
  { name: 'Computers & Laptops' },
  { name: 'Fashion' },
  { name: 'Shoes' },
  { name: 'Beauty & Personal Care' },
  { name: 'Home & Living' },
  { name: 'Kitchen & Dining' },
  { name: 'Groceries' },
  { name: 'Beverages' },
  { name: 'Health & Wellness' },
  { name: 'Sports & Fitness' },
  { name: 'Toys & Games' },
  { name: 'Books & Stationery' },
  { name: 'Baby & Kids' },
  { name: 'Automotive' },
  { name: 'Pet Supplies' },
  { name: 'Accessories' },
  { name: 'Other' },
];
